version: '3'
services:
  rpi-cluster-pxe:
    build:
      context: .
      dockerfile: config/production/Dockerfile
    environment:
      USER_UID: ${USER_UID:-1000}
      USER_GID: ${USER_GID:-1000}
    volumes:
      - ./backups:/nfs/backups
    network_mode: "host"
    privileged: true
